<header id="main-header">
    <div class="container">
        <div class="row">
            <div class="col-xs-5 col-sm-3">
                <h1 id="main-logo">
                    <a href="index.php">
                        <img src="img/logo-mini.png" alt="SAE-OnLine">
                        <span>Sistema de Aprendizaje Eléctronico</span>
                    </a>
                </h1>
            </div>
            <div class="col-xs-7 col-sm-9">
                <ul id="main-menu" class="nav nav-pills hidden-xs">
                    <li><a href="../SAE-OnLine">INICIO</a></li>
                    <li><a href="portafolio.php">PORTAFOLIO</a></li>
                    <li><a href="javascript: mostrar('#divlogin')">LOGIN</a></li>
                </ul>

                <a href="#" id="mobile-menu-button" class="btn btn-default visible-xs">
                    <span class="glyphicon glyphicon-th-list"></span>
                </a>
            </div>
        </div>
    </div>
    <div class="visible-xs">
        <ul id="mobile-main-menu">
            <li><a href="../SAE-OnLine">INICIO</a></li>
            <li><a href="portafolio.php">PORTAFOLIO</a></li>
            <li><a href="javascript: mostrar('#divlogin')">LOGIN</a></li>
        </ul>
    </div>
</header>